name: Price Updater

on:
  schedule:
    - cron: '0 19 * * *'  # runs every day at 19:00 UTC (2:00 PM your local if UTC+5)
  workflow_dispatch:      # allows manual trigger

jobs:
  update_prices:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # Step 4: Run the Python script
      - name: Run Price Updater
        run: python Price_Updater.py

      # Step 5: Commit and push updated CSV
      - name: Commit updated CSV
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add dambulla_daily.csv
          git commit -m "Update daily prices" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/yohan2001colombo/Updater.git HEAD:main


