name: Price Updater

on:
  schedule:
    - cron: '0 19 * * *'  # runs every day at 19:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  update_prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Price Updater
        run: python Price_Updater.py

      - name: Commit updated CSV
    
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add dambulla_daily.csv
          git commit -m "Update daily prices" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

